# Setup
title:               Canal
tagline:             'is Una'
description:         'Hello World'
url:                 https://woonhahaha.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Temp
  url:               Twitter
  email:             Temp

# Gems
plugins:
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
